[package]
name = "semver-test"
version = "0.1.0"
authors = ["Mathias Wagner Nielsen <mathiasvalentinwagner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
