#!/bin/sh

# A hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>

# Check whether cocogitto is installed
if ! cog bump --help >/dev/null; then
    echo 'error: please install cocogitto'
    exit 1
fi

# Check whether cargo-bump is installed
if ! cargo bump --help >/dev/null; then
    echo 'error: please install cargo-bump'
    exit 1
fi

echo '+cog bump --auto'
cog bump --auto >/dev/null
exit 0